[project]
name = "api_chat"
version = "0.1.0"
license = "MIT Lisence"
readme = "README.md"


[tool.setuptools.packages.find]
where = ["src"]
include = ["api_assistant.*", "common", "oai"]

[tool.setuptools.dynamic]
dependencies = { file = "requirements.txt" }
