info:
  contact: {}
paths:
  /balance:
    post:
      description: Gets the balance of a user given an user id
      parameters:
      - description: User id is the unique identitier of the user
        in: query
        name: userId
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
      summary: Gets the balance of a user given an user id
  /transfer:
    post:
      description: This endpoint transfers money between two user ids
      parameters:
      - description: From user Id
        in: query
        name: fromUserId
        type: string
      - description: To user Id
        in: query
        name: toUserId
        type: string
      - description: Amount to transfer
        in: query
        name: amount
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
      summary: Transfers money between two user ids
swagger: "2.0"
